### ISSUE TITLE
access vich uploader file via method

### ISSUE THREAD

**Issue by lucasgranberg** [hshn/HshnSerializerExtraBundle#2]
A nice feature would be to be able to access the vich uploader resource via a method instead of just the property. I need to be able to serve pdf file previews. Thats why I need to have some logic behind it. I tried to get it working by doing it on the doctrine event postLoad but I had no success.

This is how it could look in the config. It might explain what I am looking for more clearly.

``` yaml

hshn_serializer_extra:
    vich_uploader:
        classes:
            AppBundle\Entity\File:
                files:
                    - { property: resource, export_to: original}
                    - { accessor: getPreview, export_to: preview}
```
